-- 0005_origin_evidence — provenance as evidence, not as a single answer.
--
-- 0004 stored one resolved country per product. That shape cannot express
-- what origin data actually looks like, so this migration keeps the resolved
-- row as a summary and moves the facts into an evidence table beneath it.
--
-- Three distinctions are load-bearing and each cost us a wrong answer before
-- being modelled explicitly:
--
--   * Ingredient origin != manufacturing origin. Kraft Smooth Peanut Butter
--     is American peanuts processed in Canada. One country column has to pick
--     one, and either choice is a lie.
--   * Sources disagree. Several records for one product routinely conflict;
--     one row per product silently picks a winner. `conflicting` is a status,
--     not a country.
--   * The claim wording is legally meaningful. Under CFIA rules "Product of
--     Canada" (>=98% Canadian content) and "Made in Canada" (processed here,
--     ingredients may be imported) are different facts. Ranking by provenance
--     depends on keeping them apart, so `verbatim` holds the exact source
--     wording and is never paraphrased.
--
-- And two non-answers are kept distinct from each other and from data:
-- `unknown` (the source answered, nothing was published) vs `lookup_failed`
-- (the source did not answer — an outage or rate limit, evidence of nothing).

CREATE TABLE product_origin_evidence (
    id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id        integer NOT NULL REFERENCES products (id) ON DELETE CASCADE,
    -- open-food-facts | label-photo | retailer-pdp | guess
    source            text NOT NULL,
    -- barcode, photo filename or URL the observation came from
    source_ref        text NOT NULL DEFAULT '',
    -- product-of | made-in | prepared-in | packaged-in | grown-in | farmed-in
    -- | harvested-in | caught-in | imported | conflicting | unknown | none
    claim_type        text NOT NULL DEFAULT 'unknown',
    verbatim          text NOT NULL DEFAULT '',
    ingredient_origin text NOT NULL DEFAULT '',
    manufactured_in   text NOT NULL DEFAULT '',
    confidence        text NOT NULL DEFAULT 'low' CHECK (confidence IN ('high', 'medium', 'low')),
    -- an "Imported by ..." address is NOT a country of origin; flagged, never ranked
    importer_only     boolean NOT NULL DEFAULT false,
    note              text NOT NULL DEFAULT '',
    observed_at       text NOT NULL DEFAULT ''
);

CREATE INDEX idx_origin_evidence_product ON product_origin_evidence (product_id);
CREATE INDEX idx_origin_evidence_source  ON product_origin_evidence (source);

-- Resolved summary. `status` is what the ranking keys off; `country` stays for
-- backward compatibility with 0004 readers.
ALTER TABLE product_origins ADD COLUMN status            text    NOT NULL DEFAULT 'unknown';
ALTER TABLE product_origins ADD COLUMN claim_type        text    NOT NULL DEFAULT 'unknown';
ALTER TABLE product_origins ADD COLUMN verbatim          text    NOT NULL DEFAULT '';
ALTER TABLE product_origins ADD COLUMN ingredient_origin text    NOT NULL DEFAULT '';
ALTER TABLE product_origins ADD COLUMN manufactured_in   text    NOT NULL DEFAULT '';
ALTER TABLE product_origins ADD COLUMN evidence_count    integer NOT NULL DEFAULT 0;

-- Rows written by 0004 came from name/brand heuristics, which are inferences
-- rather than evidence. Mark them so they can never satisfy a filter.
UPDATE product_origins SET status = 'guess' WHERE source IN ('heuristic', 'llm');

-- Scraped price observations. Deliberately NOT store_products: that table is
-- the seeded synthetic catalog, while these are timestamped readings from a
-- real store page, including the branch actually shown (store selection is
-- session state resolved from the client IP, so the branch is observed, never
-- chosen). product_id is nullable because a scraped listing may match nothing
-- in the catalog, and dropping those rows would hide the miss.
CREATE TABLE price_observations (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id   integer REFERENCES products (id) ON DELETE SET NULL,
    item_query   text NOT NULL DEFAULT '',
    store        text NOT NULL DEFAULT '',
    branch       text NOT NULL DEFAULT '',
    product_name text NOT NULL DEFAULT '',
    size         text NOT NULL DEFAULT '',
    price        double precision,
    -- raw as printed: multi-unit listings are ranges and collapsing them to a
    -- single number invents precision
    price_text   text NOT NULL DEFAULT '',
    unit_price   text NOT NULL DEFAULT '',
    link         text NOT NULL DEFAULT '',
    observed_at  text NOT NULL DEFAULT '',
    run_id       text NOT NULL DEFAULT ''
);

CREATE INDEX idx_price_obs_product ON price_observations (product_id);
CREATE INDEX idx_price_obs_run     ON price_observations (run_id);
