-- 0006_origin_submissions — a reviewed queue for agent-submitted label claims.
--
-- pantry-api's MCP server gains a write path: an agent that has read a
-- package label submits a structured origin claim. Those claims land here,
-- never directly in product_origin_evidence, for three reasons:
--
--   * A pending claim must never be evidence. product_origin_evidence is the
--     trusted layer that planning filters key off; a row there changes what
--     the planner ships. A transcription nobody has checked cannot be allowed
--     to do that, so submissions live in a table the resolver does not read.
--   * Approval copies, it does not move. An approved submission produces a
--     new evidence row (source 'agent-label') and records that row's id in
--     `evidence_id`; the submission itself stays, with who reviewed it, when,
--     and why. Deleting the evidence later nulls the pointer but keeps the
--     audit trail (ON DELETE SET NULL).
--   * Rejections are data. A rejected claim is kept with its review note so
--     the same wording resubmitted later returns the earlier verdict instead
--     of re-entering the queue.
--
-- Column semantics mirror product_origin_evidence (0005): `verbatim` is the
-- exact printed wording, never a paraphrase; `importer_only` flags an
-- "Imported by ..." address, which is not an origin; `ingredient_origin` is
-- filled only for full claims (product-of, grown-in, ...) while
-- `manufactured_in` is always filled. Timestamps are ISO-8601 text, as in
-- 0005, so the API's SQLAlchemy mirror stays identical on SQLite.

CREATE TABLE origin_submissions (
    id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id        integer NOT NULL REFERENCES products (id) ON DELETE CASCADE,
    claim_type        text NOT NULL,
    country           text NOT NULL,
    ingredient_origin text NOT NULL DEFAULT '',
    manufactured_in   text NOT NULL DEFAULT '',
    verbatim          text NOT NULL,
    confidence        text NOT NULL DEFAULT 'low' CHECK (confidence IN ('high', 'medium', 'low')),
    importer_only     boolean NOT NULL DEFAULT false,
    note              text NOT NULL DEFAULT '',
    source_ref        text NOT NULL DEFAULT '',
    submitted_by      text NOT NULL DEFAULT '',
    submitted_at      text NOT NULL DEFAULT '',
    status            text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
    reviewed_by       text NOT NULL DEFAULT '',
    reviewed_at       text NOT NULL DEFAULT '',
    review_note       text NOT NULL DEFAULT '',
    evidence_id       integer REFERENCES product_origin_evidence (id) ON DELETE SET NULL
);

CREATE INDEX idx_origin_submissions_status  ON origin_submissions (status);
CREATE INDEX idx_origin_submissions_product ON origin_submissions (product_id);
