-- GENERATED FILE — do not edit by hand.
-- Regenerate with: python3 scripts/gen-seed-sql.py
-- Applied on every migration run; written to be idempotent.

BEGIN;

-- ─── products ───
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (1, 'Wheat Bread 1', 'Whole-grain wheat sandwich loaf, 675g, sliced', 5.0, 'bakery', 'bread', 'gluten', '675g', 675, 'g') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (2, 'Wheat Bread 2', 'Basic wheat sandwich loaf, 450g, sliced, store brand', 3.0, 'bakery', 'bread', 'gluten', '450g', 450, 'g') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (3, 'Dark Chocolate Cadbury', '70% cocoa dark chocolate bar, 100g, dairy-free', 5.0, 'snacks', 'chocolate', '', '100g', 100, 'g') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (4, 'Milk Chocolate Cadbury', 'Milk chocolate bar, smooth and creamy, 100g', 10.0, 'snacks', 'chocolate', 'dairy', '100g', 100, 'g') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (5, 'Nestles PBJ', 'Peanut butter and grape jelly swirl in a single jar, 340g', 8.0, 'pantry', 'spread', 'nuts', '340g', 340, 'g') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (6, 'Canadian Peanut Butter Cream', 'Smooth peanut butter, no jelly, 500g', 3.0, 'pantry', 'spread', 'nuts', '500g', 500, 'g') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (7, 'Sourdough Loaf', 'Artisanal sourdough, 600g, whole loaf uncut', 6.5, 'bakery', 'bread', 'gluten', '600g', 600, 'g') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (8, 'Basmati Rice 2kg', 'Long-grain basmati rice, 2kg bag, produced in India', 12.0, 'pantry', 'rice', '', '2kg', 2000, 'g') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (9, 'Long Grain White Rice 1kg', 'Standard long-grain white rice, 1kg bag', 4.5, 'pantry', 'rice', '', '1kg', 1000, 'g') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (10, 'Boneless Skinless Chicken Breast', 'Fresh chicken breast, boneless & skinless, ~500g package', 8.99, 'meat', 'poultry', 'meat', '500g', 500, 'g') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (11, 'Chicken Thighs Bone-In', 'Bone-in, skin-on chicken thighs, ~700g', 6.49, 'meat', 'poultry', 'meat', '700g', 700, 'g') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (12, 'Yellow Onion', 'Fresh yellow cooking onion, 1 bulb (~200g)', 0.99, 'produce', 'vegetables', '', '~200g', 200, 'g') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (13, 'Fresh Garlic', 'One bulb of fresh garlic (~50g)', 0.79, 'produce', 'vegetables', '', '~50g', 50, 'g') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (14, 'Roma Tomato', 'Fresh Roma tomatoes, 500g pack', 2.99, 'produce', 'vegetables', '', '500g', 500, 'g') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (15, 'Canned Diced Tomatoes', 'Diced tomatoes in juice, canned, 796ml', 1.99, 'pantry', 'canned', '', '796ml', 796, 'ml') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (16, 'Extra Virgin Olive Oil 500ml', 'Cold-pressed extra virgin olive oil, 500ml', 9.99, 'pantry', 'oil', '', '500ml', 500, 'ml') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (17, 'Canola Oil 1L', 'Neutral canola cooking oil, 1L', 4.49, 'pantry', 'oil', '', '1L', 1000, 'ml') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (18, 'Butter Salted 454g', 'Salted butter, 454g, from grass-fed cows', 6.99, 'dairy', 'butter', 'dairy', '454g', 454, 'g') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (19, 'Whole Milk 1L', '3.25% homogenized milk, 1L carton', 2.99, 'dairy', 'milk', 'dairy', '1L', 1000, 'ml') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (20, 'Plain Greek Yogurt 750g', 'Plain Greek yogurt, unsweetened, 750g tub', 5.99, 'dairy', 'yogurt', 'dairy', '750g', 750, 'g') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (21, 'Spaghetti Pasta 500g', 'Dry spaghetti pasta, 500g box', 2.49, 'pantry', 'pasta', 'gluten', '500g', 500, 'g') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (22, 'Ground Beef Lean', 'Lean ground beef, ~450g package, fresh', 7.99, 'meat', 'beef', 'meat', '450g', 450, 'g') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (23, 'Cheddar Cheese Block 300g', 'Sharp aged cheddar cheese, 300g block', 5.99, 'dairy', 'cheese', 'dairy', '300g', 300, 'g') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (24, 'Mozzarella Shredded 200g', 'Shredded mozzarella for pizza / pasta, 200g', 4.99, 'dairy', 'cheese', 'dairy', '200g', 200, 'g') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (25, 'Fresh Ginger', 'Fresh ginger root, sold by weight, priced per 100g', 1.29, 'produce', 'vegetables', '', '100g', 100, 'g') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (26, 'Cumin Ground 100g', 'Ground cumin spice, 100g jar', 3.49, 'pantry', 'spice', '', '100g', 100, 'g') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (27, 'Turmeric Ground 100g', 'Ground turmeric spice, 100g jar', 3.99, 'pantry', 'spice', '', '100g', 100, 'g') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (28, 'Coriander Ground 100g', 'Ground coriander spice, 100g jar', 3.49, 'pantry', 'spice', '', '100g', 100, 'g') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (29, 'Garam Masala 100g', 'Traditional Indian spice blend, 100g', 4.99, 'pantry', 'spice', '', '100g', 100, 'g') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (30, 'Frozen Broccoli 500g', 'Frozen broccoli florets, 500g bag', 3.49, 'frozen', 'vegetables', '', '500g', 500, 'g') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (31, 'Tomato Sauce Jar 650ml', 'Classic marinara tomato sauce for pasta, 650ml jar', 3.99, 'pantry', 'sauce', '', '650ml', 650, 'ml') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (32, 'Tomato Paste 156ml', 'Double-concentrated tomato paste, 156ml can', 1.29, 'pantry', 'canned', '', '156ml', 156, 'ml') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (33, 'Crushed Tomatoes Canned 796ml', 'Canned crushed tomatoes, no salt added, 796ml', 2.29, 'pantry', 'canned', '', '796ml', 796, 'ml') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (34, 'Passata Strained Tomatoes 680ml', 'Ground strained tomatoes (passata), glass bottle, 680ml', 2.79, 'pantry', 'sauce', '', '680ml', 680, 'ml') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (35, 'Ground Beef Medium 900g', 'Medium ground beef, family value pack, ~900g', 11.99, 'meat', 'beef', 'meat', '900g', 900, 'g') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (36, 'Ground Beef Extra Lean 300g', 'Extra lean ground beef, small pack, ~300g', 6.49, 'meat', 'beef', 'meat', '300g', 300, 'g') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (37, 'Russet Potatoes 5lb Bag', 'Russet potatoes for baking and mashing, 5lb (2.27kg) bag', 4.99, 'produce', 'vegetables', '', '2.27kg', 2270, 'g') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (38, 'Baby Potatoes 680g', 'Creamer baby potatoes, 680g bag', 3.99, 'produce', 'vegetables', '', '680g', 680, 'g') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (39, 'Oat Milk 1L', 'Unsweetened oat beverage, dairy-free, 1L carton', 3.49, 'dairy', 'milk', '', '1L', 1000, 'ml') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (40, 'Almond Milk 946ml', 'Unsweetened almond beverage, dairy-free, 946ml', 3.29, 'dairy', 'milk', 'nuts', '946ml', 946, 'ml') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (41, 'Vegan Cheese Shreds 200g', 'Plant-based mozzarella-style shreds, dairy-free, 200g', 5.49, 'dairy', 'cheese', 'soy', '200g', 200, 'g') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (42, 'Coconut Yogurt 500g', 'Plain coconut-based yogurt alternative, dairy-free, 500g', 5.99, 'dairy', 'yogurt', '', '500g', 500, 'g') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (43, 'Parmesan Wedge 200g', 'Aged parmesan cheese wedge, 200g', 7.99, 'dairy', 'cheese', 'dairy', '200g', 200, 'g') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (44, 'Cheddar Shredded 320g', 'Shredded mild cheddar, resealable bag, 320g', 6.99, 'dairy', 'cheese', 'dairy', '320g', 320, 'g') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (45, 'Whole Chicken 1.6kg', 'Whole roasting chicken, ~1.6kg', 12.99, 'meat', 'poultry', 'meat', '1.6kg', 1600, 'g') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (46, 'Chicken Thighs Boneless 450g', 'Boneless skinless chicken thighs, ~450g', 7.49, 'meat', 'poultry', 'meat', '450g', 450, 'g') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (47, 'Atlantic Salmon Fillet 400g', 'Fresh Atlantic salmon fillet, ~400g', 13.99, 'meat', 'seafood', 'meat', '400g', 400, 'g') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (48, 'Canned Tuna Flaked 170g', 'Flaked light tuna in water, canned, 170g', 1.79, 'pantry', 'canned', 'meat', '170g', 170, 'g') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (49, 'Gluten-Free Penne 340g', 'Corn and rice gluten-free penne, 340g', 4.49, 'pantry', 'pasta', '', '340g', 340, 'g') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (50, 'Gluten-Free Bread 400g', 'Gluten-free sandwich loaf, 400g, sliced', 6.99, 'bakery', 'bread', 'egg', '400g', 400, 'g') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (51, 'Penne Rigate 500g', 'Dry penne rigate pasta, 500g box', 2.29, 'pantry', 'pasta', 'gluten', '500g', 500, 'g') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (52, 'Fusilli Family Pack 900g', 'Dry fusilli pasta, family value pack, 900g', 3.79, 'pantry', 'pasta', 'gluten', '900g', 900, 'g') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (53, 'Broccoli Crown', 'Fresh broccoli crown, ~400g', 2.49, 'produce', 'vegetables', '', '~400g', 400, 'g') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (54, 'Carrots 1kg', 'Fresh carrots, 1kg bag', 2.29, 'produce', 'vegetables', '', '1kg', 1000, 'g') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (55, 'Bell Pepper Trio', 'Three sweet bell peppers (red/yellow/orange), ~500g', 4.99, 'produce', 'vegetables', '', '~500g', 500, 'g') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (56, 'Fresh Basil 30g', 'Fresh basil herb bunch, 30g clamshell', 2.99, 'produce', 'herbs', '', '30g', 30, 'g') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (57, 'Chicken Stock 900ml', 'Low-sodium chicken stock, 900ml carton', 2.49, 'pantry', 'canned', 'meat', '900ml', 900, 'ml') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (58, 'Coconut Milk Canned 400ml', 'Full-fat coconut milk, canned, 400ml', 2.29, 'pantry', 'canned', '', '400ml', 400, 'ml') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (59, 'Soy Sauce 500ml', 'Naturally brewed soy sauce, 500ml', 3.99, 'pantry', 'sauce', 'soy,gluten', '500ml', 500, 'ml') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (60, 'Eggs Large Dozen', '12 large white eggs', 4.29, 'dairy', 'eggs', 'egg', '12', 12, 'each') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (61, 'All-Purpose Flour 2.5kg', 'All-purpose wheat flour, 2.5kg bag', 5.49, 'pantry', 'baking', 'gluten', '2.5kg', 2500, 'g') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;
INSERT INTO products (id, name, description, price, category, subcategory, dietary_tags, unit_size, unit_qty, unit_uom) VALUES (62, 'Olive Oil 1L', 'Pure olive oil, everyday cooking grade, 1L', 13.99, 'pantry', 'oil', '', '1L', 1000, 'ml') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, category = EXCLUDED.category, subcategory = EXCLUDED.subcategory, dietary_tags = EXCLUDED.dietary_tags, unit_size = EXCLUDED.unit_size, unit_qty = EXCLUDED.unit_qty, unit_uom = EXCLUDED.unit_uom;

-- ─── recipes ───
INSERT INTO recipes (slug, name, servings) VALUES ('pbj_sandwich', 'Peanut Butter & Jelly Sandwich', 2) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, servings = EXCLUDED.servings;
INSERT INTO recipes (slug, name, servings) VALUES ('spaghetti_bolognese', 'Spaghetti Bolognese', 4) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, servings = EXCLUDED.servings;
INSERT INTO recipes (slug, name, servings) VALUES ('chicken_curry', 'Simple Chicken Curry', 4) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, servings = EXCLUDED.servings;
INSERT INTO recipes (slug, name, servings) VALUES ('grilled_cheese', 'Grilled Cheese Sandwich', 1) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, servings = EXCLUDED.servings;
INSERT INTO recipes (slug, name, servings) VALUES ('veggie_stirfry', 'Vegetable Stir Fry', 2) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, servings = EXCLUDED.servings;

-- ─── recipe_ingredients (delete + re-insert per recipe) ───
DELETE FROM recipe_ingredients WHERE recipe_slug = 'pbj_sandwich';
INSERT INTO recipe_ingredients (recipe_slug, line_no, name, category) VALUES ('pbj_sandwich', 1, 'Peanut Butter and Jelly Jam', 'spread');
INSERT INTO recipe_ingredients (recipe_slug, line_no, name, category) VALUES ('pbj_sandwich', 2, 'Wheat Bread', 'bread');
INSERT INTO recipe_ingredients (recipe_slug, line_no, name, category) VALUES ('pbj_sandwich', 3, 'White Chocolate', 'chocolate');
DELETE FROM recipe_ingredients WHERE recipe_slug = 'spaghetti_bolognese';
INSERT INTO recipe_ingredients (recipe_slug, line_no, name, category) VALUES ('spaghetti_bolognese', 1, 'Spaghetti', 'pantry');
INSERT INTO recipe_ingredients (recipe_slug, line_no, name, category) VALUES ('spaghetti_bolognese', 2, 'Ground Beef', 'meat');
INSERT INTO recipe_ingredients (recipe_slug, line_no, name, category) VALUES ('spaghetti_bolognese', 3, 'Yellow Onion', 'produce');
INSERT INTO recipe_ingredients (recipe_slug, line_no, name, category) VALUES ('spaghetti_bolognese', 4, 'Garlic', 'produce');
INSERT INTO recipe_ingredients (recipe_slug, line_no, name, category) VALUES ('spaghetti_bolognese', 5, 'Canned Tomatoes', 'pantry');
INSERT INTO recipe_ingredients (recipe_slug, line_no, name, category) VALUES ('spaghetti_bolognese', 6, 'Olive Oil', 'oil');
INSERT INTO recipe_ingredients (recipe_slug, line_no, name, category) VALUES ('spaghetti_bolognese', 7, 'Mozzarella', 'dairy');
DELETE FROM recipe_ingredients WHERE recipe_slug = 'chicken_curry';
INSERT INTO recipe_ingredients (recipe_slug, line_no, name, category) VALUES ('chicken_curry', 1, 'Chicken Thighs', 'meat');
INSERT INTO recipe_ingredients (recipe_slug, line_no, name, category) VALUES ('chicken_curry', 2, 'Basmati Rice', 'grain');
INSERT INTO recipe_ingredients (recipe_slug, line_no, name, category) VALUES ('chicken_curry', 3, 'Yellow Onion', 'produce');
INSERT INTO recipe_ingredients (recipe_slug, line_no, name, category) VALUES ('chicken_curry', 4, 'Garlic', 'produce');
INSERT INTO recipe_ingredients (recipe_slug, line_no, name, category) VALUES ('chicken_curry', 5, 'Ginger', 'produce');
INSERT INTO recipe_ingredients (recipe_slug, line_no, name, category) VALUES ('chicken_curry', 6, 'Garam Masala', 'spice');
INSERT INTO recipe_ingredients (recipe_slug, line_no, name, category) VALUES ('chicken_curry', 7, 'Turmeric', 'spice');
INSERT INTO recipe_ingredients (recipe_slug, line_no, name, category) VALUES ('chicken_curry', 8, 'Diced Tomatoes', 'pantry');
INSERT INTO recipe_ingredients (recipe_slug, line_no, name, category) VALUES ('chicken_curry', 9, 'Canola Oil', 'oil');
DELETE FROM recipe_ingredients WHERE recipe_slug = 'grilled_cheese';
INSERT INTO recipe_ingredients (recipe_slug, line_no, name, category) VALUES ('grilled_cheese', 1, 'Sliced Bread', 'bread');
INSERT INTO recipe_ingredients (recipe_slug, line_no, name, category) VALUES ('grilled_cheese', 2, 'Cheddar Cheese', 'dairy');
INSERT INTO recipe_ingredients (recipe_slug, line_no, name, category) VALUES ('grilled_cheese', 3, 'Butter', 'dairy');
DELETE FROM recipe_ingredients WHERE recipe_slug = 'veggie_stirfry';
INSERT INTO recipe_ingredients (recipe_slug, line_no, name, category) VALUES ('veggie_stirfry', 1, 'Broccoli', 'produce');
INSERT INTO recipe_ingredients (recipe_slug, line_no, name, category) VALUES ('veggie_stirfry', 2, 'Basmati Rice', 'grain');
INSERT INTO recipe_ingredients (recipe_slug, line_no, name, category) VALUES ('veggie_stirfry', 3, 'Garlic', 'produce');
INSERT INTO recipe_ingredients (recipe_slug, line_no, name, category) VALUES ('veggie_stirfry', 4, 'Ginger', 'produce');
INSERT INTO recipe_ingredients (recipe_slug, line_no, name, category) VALUES ('veggie_stirfry', 5, 'Canola Oil', 'oil');

COMMIT;
